apiVersion: v1
kind: Secret
metadata:
  name: student-service-secret
  namespace: escola-qapabilities
  labels:
    app.kubernetes.io/name: student-service
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded values - SUBSTITUTE WITH YOUR ACTUAL VALUES
  # Database Connection String
  STUDENT_DB_CONNECTION_STRING: U2VydmVyPXNxbC1zZXJ2ZXItc2VydmljZS5lc2NvbGEtcWFwYWJpbGl0aWVzLnN2Yy5jbHVzdGVyLmxvY2FsLDE0MzM7RGF0YWJhc2U9RXNjb2xhUUFwYWJpbGl0aWVzU3R1ZGVudFNlcnZpY2U7VXNlciBJZD1TQTtQYXNzd29yZD1Fc2NvbGFRQXBhYmlsaXRpZXMxMjMhO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZTtFbmNyeXB0PWZhbHNlOw==
  
  # JWT Secret Key - MUST BE 32+ characters and properly encoded
  JWT_KEY: ZXNjb2xhLXFhcGFiaWxpdGllcy1zdXBlci1zZWNyZXQtand0LWtleS1mb3ItcHJvZHVjdGlvbi0zMi1jaGFycy1taW5pbXVtLWtleQ==

---
# NOTE: To create secrets properly, use:
# kubectl create secret generic student-service-secret \
#   --from-literal=STUDENT_DB_CONNECTION_STRING="Server=sql-server-service.escola-qapabilities.svc.cluster.local,1433;Database=EscolaQApabilitiesStudentService;User Id=SA;Password=YOUR_STRONG_PASSWORD;TrustServerCertificate=true;Encrypt=false;" \
#   --from-literal=JWT_KEY="your-super-secret-jwt-key-for-production-32-chars-minimum" \
#   -n escola-qapabilities

