---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
  namespace: escola-qapabilities
  labels:
    app.kubernetes.io/name: sql-server
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi

---
apiVersion: v1
kind: Secret
metadata:
  name: sql-server-secret
  namespace: escola-qapabilities
  labels:
    app.kubernetes.io/name: sql-server
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded: EscolaQApabilities123!
  SA_PASSWORD: RXNjb2xhUUFwYWJpbGl0aWVzMTIzIQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: escola-qapabilities
  labels:
    app.kubernetes.io/name: sql-server
    app.kubernetes.io/component: database
    app.kubernetes.io/version: "2022"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sql-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sql-server
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
          name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Express"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: sql-server-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
  namespace: escola-qapabilities
  labels:
    app.kubernetes.io/name: sql-server
    app.kubernetes.io/component: service
spec:
  selector:
    app.kubernetes.io/name: sql-server
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql
  type: ClusterIP

